### ISSUE TITLE
Deduct points when RS is reset

### ISSUE THREAD

**Issue by morxa** [robocup-logistics/rcll-refbox#1]
According to the rules, the points for feeding in bases into a RS should be deducted if the RS is reset. Currently, the points are not deducted.

**Comment by thomerz** [comment]
But points should only be deducted for additional material that was not consumed already when mounting rings, right?

**Comment by MostafaGomaa** [comment]
Correct, materials used in production are no longer in the machines, hence outside of the scope

**Comment by MostafaGomaa** [comment]
solved by PR #26. I shall close the issue once PR is accepted
