### ISSUE TITLE
Include MongoDB in Ubuntu CircleCI builds

### ISSUE THREAD

**Issue by timn** [robocup-logistics/rcll-refbox#11]
Current CircleCI builds on Ubuntu do not include MongoDB support. Since this is crucial during tournaments, and we may end up with a Ubuntu machine, build with MongoDB integration. Probably requires extended the prerequisites?

**Comment by timn** [comment]
Want to open a PR for your branch?

**Comment by morxa** [comment]
No, it's not working yet. Ubuntu is confusing with their package names, this was the wrong driver.

**Comment by morxa** [comment]
But while I'm working on it, we may switch Bionic Beaver, the latest LTS release. What do you think?

**Comment by timn** [comment]
Yes, I'm happy to move to whatever the latest LTS is. [CLIPS packages](https://launchpad.net/~timn/+archive/ubuntu/clips/+packages) are ready.

And CircleCI confused me, I checked the Fedora build which worked just fine, only MongoDB did not. That's why I asked for the PR in the first place. Just request a review once you are done.
