### ISSUE TITLE
Dockercontainer llsf-refbox -h

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/rcll-refbox#115]
Hi,

I just tried out the new version with the new config handeling, if I build the Dockerfile and then run it, the refbox crashes with a segfault.

```
[root@grips-simpc-left /]# llsf-refbox -h
Segmentation fault (core dumped)
[root@grips-simpc-left /]# 
```

@TarikViehmann  can you test if this also happens for you?

**Comment by TarikViehmann** [comment]
Indeed, sorry! I forgot to update the Dockerfile, should work with the update in https://github.com/robocup-logistics/rcll-refbox/pull/116

**Comment by pkohout** [comment]
problem is fixed :D
