### ISSUE TITLE
Refbox OPC-UA communication

### ISSUE THREAD

**Issue by morxa** [robocup-logistics/rcll-refbox#14]
Replace the communication to the MPS machines with a OPC-UA communication based on [open62541](https://github.com/open62541/open62541).

For testing, use the mockup developed in robocup-logistics/rcll-mps-stations#1.

**Comment by morxa** [comment]
The [open62541 library is available on Fedora](https://src.fedoraproject.org/rpms/open62541). I started to co-maintain the package to make sure that the package is in good shape. I also [updated the package](https://src.fedoraproject.org/rpms/open62541/pull-request/2) to the latest release.

**Comment by timn** [comment]
You should also check Ubuntu or provide a PPA (similar to my CLIPS PPA). We had Ubuntu installed on the provided referee box machines a couple times in the past.

**Comment by morxa** [comment]
As discussed yesterday in a meeting, we will first merge the current `master` into [`new-mps-communication`](https://github.com/robocup-logistics/rcll-refbox/tree/common/new-mps-communication) and start working from there. This allows us to use the new communication protocol between refbox and MPS stations and directly implement OPC-UA communication with the new protocol instead of replacing modbus with OPC-UA in the old protocol.

For this, I first want #16 to be merged into master, as it may bring additional conflicts.
