### ISSUE TITLE
Track workpieces

### ISSUE THREAD

**Issue by morxa** [robocup-logistics/rcll-refbox#15]
Assuming that the barcode reader provides us with a workpiece ID at every MPS, keep track of the workpieces in the refbox and assign partial points for production steps according to the rules.

**Comment by timn** [comment]
Part of this has been implemented in the `timn/workpiece-tracking` branch.

**Comment by morxa** [comment]
@MostafaGomaa have you had a look already?

**Comment by MostafaGomaa** [comment]
I will be looking into this over the next few days

**Comment by morxa** [comment]
@MostafaGomaa, can you give a status update? Will this be ready for the German Open?

**Comment by MostafaGomaa** [comment]
progress is currently tacked in branch  'mgomaa/workpiece-tracking'
Aside from some open questions, we should be able to test _at least_  partial functionality soon 

some open question appreciating input :
[1] How to confirm the cap-color to award intermediate points for mounting a cap  (cap-color/mps allocation is team specific choice) 
  -->  sol 1. ask:  confirmation msg to referee (like we do on delivery)
  -->  sol 2. generous:  give mount-cap points whenever any cap is mounted (regardless order or color)
  -->  sol 3. delay:  defer the point and give them on delivery (when confirmed by referee)

[2] how does it work with the barcode reader and the register responsible for it.  Do we only get the last scanned value every time we check? Or can we also determine if the Workpiece is currently visible by the reader or not?

**Comment by MostafaGomaa** [comment]
Partial implementation and progress currently tracked in PR #29

**Comment by morxa** [comment]
Implemented in #15.
