### ISSUE TITLE
Machines during Exploration

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/rcll-refbox#158]
Right now there is no way for a team to know if they reported a machine correctly (only possible to look at points). Is is possible to merge the following branch: https://github.com/robocup-logistics/rcll-refbox/tree/dswoboda/send-gt-on-report then a team would know for sure if they reported a machine correctly.

**Comment by snoato** [comment]
Rules prohibit us from sending the ground truth but you should already get MachineReportInfo messages, which you should only get if you report correctly.
