### ISSUE TITLE
Send orders via Websocket at reconnect

### ISSUE THREAD

**Issue by greedykangaroo01** [robocup-logistics/rcll-refbox#166]
Currently, information about the orders is sent in the beginning and after reconnect - but only when production has started. This leads to the effect that order info is not available when a new connection was made after setup but before production has started and does the frontend does not know about the upcoming orders. Thus, information about the orders should be send at every reconnect, not only after production has started. The UI might make the decision what info do display in which phases.

**Comment by snoato** [comment]
Order information should not be visible during the setup phase. I will change the backend code such that it is only sent out during the production phase.
