### ISSUE TITLE
Assign color to cap station and send via Websocket

### ISSUE THREAD

**Issue by greedykangaroo01** [robocup-logistics/rcll-refbox#167]
Similar to the ring station, a new property should be created that represents the cap station's shelf. E.g.
```
shelf: Array<{base_color: string, cap_color: string}> = [
  {
    base_color: 'BASE_RED',
    cap_color: 'CAP_GREY'
  },
  {
    base_color: 'BASE_BLACK',
    cap_color: 'CAP_BLACK'
  }
]
```
This should be added to the machine's websocket message in order for the new frontend to be able to show the current shelf on a cap station.

**Comment by snoato** [comment]
Bases on the cap station are always of color none, as they are not the same as bases of the base station. Ring color configurations can be freely chosen by the teams at setup and during each refill. This information is not shared with the refbox at any point, therefore it can't provided.
