### ISSUE TITLE
Send correct time with attention messages

### ISSUE THREAD

**Issue by greedykangaroo01** [robocup-logistics/rcll-refbox#171]
While all other websocket messages provide a 'time' property, messages of type 'attention' currently also have this property but it does not represent the correct time (during testing values were e.g. 5 or 10). I don't know what these values represent but it is absolutely necessary to also send the correct time like for any other message for the new frontend.

**Comment by snoato** [comment]
Attention messages are not equivalent to normal log messages. Rather, they represent special information that should be clearly visible as they indicate some important event happening in the game (e.g., the start of production phase or a robot losing connection). The fact that the field is called `time` seems to be a mistake actually, as in the original protobuf interface it was called `time-to-show`. It indicates how long the message should be visible on the interface. I can add an additional field showing the actual time for you, probably, but I am unsure why this would be **absolutely necessary** given the intent usage of attention messages.

**Comment by greedykangaroo01** [comment]
Renaming the time property to time-to-show and and also providing the time would be ideal. As written, the time would not be displayed but is needed to align with some other major code restructuring I did to make more use of computed properties and align with Vue3 design principles.

**Comment by snoato** [comment]
I'm about to create a PR that addresses this issue. Since it would change the field names in a message, it would be great if you could do a small fixup PR for the current frontend to ensure compatibility until the new frontend is finished. Concretely there will be a float `game_time` just like in the `gamestate` messages and the old `time` is renamed to `time_to_display`.

**Comment by greedykangaroo01** [comment]
Great. As I am not that experienced with git yet, I will probably create this PR during the next meeting on Thursday

**Comment by greedykangaroo01** [comment]
Looks like I do not even have to make a fixup PR since the time property was ignored in the frontend on the current master branch. Instead it was hardcoded to show the message for 6 seconds. I will now only implement it with the new frontend.
