### ISSUE TITLE
Remove zero points notifcations

### ISSUE THREAD

**Issue by greedykangaroo01** [robocup-logistics/rcll-refbox#175]
Sometimes, zero points are awarded for specific actions like robot maintenance. According to Tarik, this might be because of these actions actually rewarding some (minus) points in other versions of the rule book. But as e.g. robot maintenance is visible in other parts of the UI, this information is not needed to clutter the points history, so it might make sense to already filter these messages out/ not even sending them in the refbox. However, if there are good reasons to send these points messages, please enlighten me :)

**Comment by snoato** [comment]
The current iteration of the rules states the following:
"The first maintenance per robot is free, while the second maintenance for any robot needs to be purchased costing 5 points."

My opinion on this: points are more something like a currency (and definitely will be even more so in the future). The code is implemented in a way that works regardless of the (configurable) penalty, therefore it would require some specific exception to not award 0 points. The points history is also not related to information about a robot's state. So referees already knowing the robots' states through different means is not really relevant to the points history. Those two things convey two very distinct aspects of the game. Additionally, I think keeping the 0 points is nice for bookkeeping (you can see that the free maintenance was already "bought").

@TarikViehmann what are your thoughts on this?

**Comment by TarikViehmann** [comment]
I personally am not bothered by zero point stuff, especially for maintenance where it kinda makes sense.
