### ISSUE TITLE
After confirming a delivery during POST_GAME, order is not updated

### ISSUE THREAD

**Issue by greedykangaroo01** [robocup-logistics/rcll-refbox#176]
If an order needs confirmation just before the end of the production phase, chances might be that the referee confirms this order after the end of this phase, thus during POST_GAME.  The refbox responds with the corresponding points but not with an updated order (as happens during the production phase), thus the just confirmed delivery does not disappear from 'unconfirmed_deliveries'.
As the confirm deliveries popups are rendered based on the currently unconfirmed orders, this currently prevents them from closing during the POST_GAME and makes the UI unusable . Of course it would be possible to also remove the unconfirmed delivery property locally in the frontend but it would be less neat.

**Comment by snoato** [comment]
The issue isn't that we don't update the order facts after the production phase ended, it is that we do not send order facts in post game generally. But that's easy to fix!
