### ISSUE TITLE
Further improve MongoDB report format

### ISSUE THREAD

**Issue by greedykangaroo01** [robocup-logistics/rcll-refbox#183]
In addition to the changes related to the game history and config previously proposed and implemented, I propose some additional changes useful for the new frontend:

[1] While `gamestate_history` is now perfectly usable, it still contains redundant information in form of the `fact_string` and the `gamestate_fact`. If there is a reason to keep these, just ignore this point.

[2] In some places like the objects inside the `agent_task_history`, `'nil'` is used to indicate that a property is not applicable. Instead of using a string, I'd suggest to use the MongoDB-native `undefined` type which is then easier to parse.

[3] Inside the `agent_task_history`, the value of `task_parameters` currently is an array of strings with every second element being a key and the other a value. It would make sense to use an object instead of the array.

[4] Still inside the `agent_task_history`, the property `ring_color` should be renamed to `ring_colors`.

[5] Information about the machines is currently spread across multiple arrays with some information being duplicated and some information missing. I suggest a new storage format that integrates machine type dependent information with general information. While I also think this is the most readable format, it is also easier to process the data in the frontend and it reduces the mass of duplicate information. In detail I propose:

(5.1) Currently, meta information about the storage station (thus which items are in which shelf slots) is stored inside `machine_ss_shelf_slots`. This information reflects the state of the storage station at the end of the game and no conclusions about the history of the shelf may be drawn. Since from a user's perspective a storage station's shelf is just machine state information just like a ring station's payment state (though I do not know if it is implemented like that in the Refbox), I think this information is kept best with the other machine information (see 5.2 and 5.3), thus the `machine_ss_shelf_slots` is not needed. Independent from that, instead of storing the workpiece configuration inside a single `description` string, I suggest to separate it into the different properties seen in other places, `base_color`, `ring_colors` and `cap_color`. 

(5.2) Keep the `machines` array mostly as is but add initial machine-specific configuration to it and remove the root-level `machine_meta` array. Even though this would deviate from the general approach to mostly translate single clips facts into the document and is more work to implement in the backend, keeping this information separate is less intuitive from a user perspective. The `machines` information has to be put together with the type-dependent information anyway and I think it would be more clear to already have this in the DB instead of storing it separately and doing this work in the frontend. The web socket already bundles this information anyway. An item in the `machines` array could have the format:
```
name: String,
team: String,
mtype: String,
state: String,
pose: [Number, Number, Number]
zone: String,
rotation: Number,
meta: Object (depends on station type)
```
with `meta` containing the initial configuration previously found inside `machine_meta`. For example, this would mean for ring stations:
```
...
meta: {
  rs_ring_colors: [String, String]
  rs_ring_color: null/undefined
  bases_added: 0
  based_used: 0
}
```
or for storage stations (proposed):
```
...
meta: {
  slots: Array<{
    position: [Number, Number]
    base_color: String
    ...
  }>
}
```
while for all other machine types the `meta` information would just be empty. All other properties may (and many of them definitely should) be omitted.

(5.3) The `machine_history` array currently contains a lot of redundant information since it e.g. also sends the whole machine fact each time. I suggest that an item in the `machine_history` array should be of the following format:
```
name: String
state: String
game_time: Number
meta_delta: Object (depends on station type)
```
I removed the `is_latest` property since from my point of view it is not needed. I also do not need the `machine_fact` info. Whenever either the state or some meta information of the machine changes, a new item with this format should be added to the `machine_history`. Because the amount of meta information can be rather large (e.g. it would contain the whole shelf for storage stations), not the whole meta object should be sent but instead only changes within. So if e.g. a slot inside a storage station has changed, the following might be added to the history instead of the whole meta object:
```
name: 'C-SS'
state: 'PROCESSING'
game_time: 45.993003
meta_delta: {
  slot: {
    position: [3, 4]
    is_filled: false
    ...
  }
}
...
```
However, I am not sure of the exact format and open to new suggestions. I also thought about having different arrays for different machine types' meta information at root level but imo this would clutter the document too much. This was the best compromise between clarity and feasability I could think of as of now but please feel free to leave some constructive criticism.

**Comment by greedykangaroo01** [comment]
(5.4) A small additional imprecision I spotted is that, in the game report, the delivery station references the currently processed order (currently in the `machine_history` array) via the property name `order_id` while the websocket uses `ds_order`. I suggest changing the property name in the game report since all other station-specific properties also have the station type as a prefix.

**Comment by TarikViehmann** [comment]
Fixed through https://github.com/robocup-logistics/rcll-refbox/pull/180.
