### ISSUE TITLE
Docker docs + missing Readme

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/rcll-refbox#184]
Hi,
today I did not find in the rcll-refbox repo where are the docker images (on quay.io). Took quite some time to remember to go to the wiki
(https://github.com/robocup-logistics/rcll-refbox/wiki/Usage), but aren't the docker images used there obsolete? They seem to still point to the one on hub.docker.com. I just want to make sure that there are not some other docs/upgraded docs. If not I am happy to provide a PR. Just wanted to make sure that I do double work.

regards,

Peter

**Comment by TarikViehmann** [comment]
Indeed, the registry prefix for quay is missing and that might try to pull from hub.docker.com depending on your local registry setup.
Great catch, I updated that page to now include the quay prefix.
