### ISSUE TITLE
Quay.io image not updated

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/rcll-refbox#185]
Hi,

I just noticed that the newest image on quay.io is 10(tag: refactored) Months old, tag master is even 1 year old. Latest commit on the master in this repository is 10 Months ago. I could provide a PR with a build on github actions (similar to the one running on the rcll-refbox-frontend), but it would push to the Github registry.

I just noticed that some stuff if only pushed to the GitHub container registry, some only to quay.io, some to both.... I guess we should decide on one and streamline it. Then we could also add it to the rcll-get started repository where to find the images.

**Comment by TarikViehmann** [comment]
I finally got around to look into it, seems like the triggers were automatically disabled while Dominik was working on the opcua refactoring. Quay disables the trigger hooks if too many builds fail.
I fixed it now and triggered a new build for the latest master.

**Comment by TarikViehmann** [comment]
ah okay it was a bit more complicated, the trigger itself was also broken for some reason, it refused to build stuff. After creating a new trigger it works again now.
This in turn showed me that my PR https://github.com/robocup-logistics/rcll-refbox/pull/179 actually broke our docker images, looking into the reason why, will fix it tomorrow...
