### ISSUE TITLE
Communicate agent tasks via WebSocket

### ISSUE THREAD

**Issue by greedykangaroo01** [robocup-logistics/rcll-refbox#187]
Currently, agent tasks are not communicated via the WebSocket and thus relevant information what robots and machines are currently doing can not be displayed/visualized besides the robot's position.
In the frontend, I currently store agent tasks as a property of the robots as there is an (0..1)-1 relationship between robots and agent tasks. As such, it would make sense to also communicate agent tasks this way (as a robot property `agent_task`) via the WebSocket. Each time an agent task changes (also if a robot's agent task is finished but it has no new task assigned), a whole new robot object should be sent with the updated `agent_task` property. While this provides some unnecessary overhead , this is the way it is also currently done with changes in (e.g.) the `pose` and keeps the code clean for now.

**Comment by snoato** [comment]
After discussion with @TarikViehmann, we will send agent-task messages separate from the robot-info. Agent-tasks are persistent on the refbox side (to store a robot's history), uniquely identifiable, and potentially overlapping (in different states of execution). 

The upcoming PR #188 will send an agent task message mirroring the an existing agent-task fact on the refbox, whenever such a fact is created or updated.

**Comment by TarikViehmann** [comment]
Fixed through https://github.com/robocup-logistics/rcll-refbox/pull/180.
