### ISSUE TITLE
SS positioning may make the machine inaccessible

### ISSUE THREAD

**Issue by morxa** [robocup-logistics/rcll-refbox#2]
The positioning of the SS is buggy. It allows the SS to be positioned such that it is facing the wall, therefore the machine is inaccessible.

**Comment by morxa** [comment]
I'm actually not sure which way it is: @chde Is the SS accessed from the input or from the output side?

**Comment by chde** [comment]
Currently only output side, but could/should be both sides for outgoing goods. Mid-term we should allow teams to store items.

**Comment by thomerz** [comment]
We discussed this in today's TC meeting. I already updated the gecode file such that both input and output side of a SS need to be blocked. I will file a pull-request after testing my changes.

**Comment by morxa** [comment]
The required rule change to block both sides was proposed in robocup-logistics/rcll-rulebook#11.

**Comment by morxa** [comment]
@thomerz What's the status here? Could you file a PR for your changes?

**Comment by thomerz** [comment]
@morxa sorry I am quite busy at the moment since we have an upcoming EU review on Mon/Tue. I will file the PR on Tuesday on my way to Magdeburg.

**Comment by morxa** [comment]
Fixed in #28
