### ISSUE TITLE
There are no files at rcll-protobuf-msgs

### ISSUE THREAD

**Issue by wadaru** [robocup-logistics/rcll-refbox#207]
After clone rcll-refbox via git.
There are no files at rcll-refbox/src/msgs/rcll-protobuf-msgs because it is link to rcll-protobuf-msgs.
So, make cannot complete.
The error message is "/buildenv/src/libs/mps_comm/machine.h:23:10: fatal error: msgs/MachineDescription.pb.h: No such file or directory"

**Comment by TarikViehmann** [comment]
the msgs are part of a git submodule, so make sure to run `git submodule update --init` after cloning or clone with  `--recurse-submodules` flag

**Comment by wadaru** [comment]
Thanks a lot!

**Comment by wadaru** [comment]
I use the following code to avoid this problem.
However your comments is better solution than me.
`RUN rm -rf /buildenv/src/msgs/rcll-protobuf-msgs
RUN cd /buildenv/src/msgs && git clone https://github.com/robocup-logistics/rcll-protobuf-msgs`
