### ISSUE TITLE
No points at all for early delivery

### ISSUE THREAD

**Issue by thomerz** [robocup-logistics/rcll-refbox#24]
If an early delivery happens, there are 0 points awarded for the whole product. Shouldn't the production points be awarded and just all 20 delivery points deducted?

At least if we have intermediate points it would be the case anyhow that you get points for any work-task and just not get any points for the delivery since it was too early.

**Comment by MostafaGomaa** [comment]
I agree. I believe this should be the case.
This will be handled in the [mgomaa/workpiece tracking]  branch which will hopefully be ready soon
 (ie, intermediate points will be given on early delivery even when workpiece tracking is disabled)
related to #15

**Comment by MostafaGomaa** [comment]
solved by #29. I will close this issue once PR is accepted
