### ISSUE TITLE
outdated documentation, machines states unclear

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/rcll-refbox#54]
Hi,
is there some kind of documentation, we noticed that now the BaseStation goes into the state RETRIVED and stays there (not going back to IDLE any more). Is this intended? All this happens in the simulation. Should it be possible to prepare the machine while it is in the RETRIVED state? Or do we have to do something to get it back to IDLE?

![image](https://user-images.githubusercontent.com/5959988/69281355-6e5b0b00-0be8-11ea-9535-a208c623754b.png)

The machine notices that the workpiece has been picked up, so I guess the configuration for the refbox and rcll-gazebo should be fine. Even though we now have mps/enabled = true and the mps/STATION/connection = mockup. Otherwise the machines do not spawn in gazebo. We noticed that apparently there it is also a valid option to set the connection to simulation, but no idea what that does.

I am thankful for any kind of help,

regards,
Peter

**Comment by morxa** [comment]
Which version of the refbox are you using? This looks like an old version, this is how the output should look like on the current master:
```
16:27:35.094993 C: Received prepare for C-BS
16:27:35.095295 C: C-BS is IDLE, processing prepare
16:27:35.095513 C: Prepared C-BS (side: OUTPUT, color: BASE_RED)
16:27:35.096619 C: Machine C-BS dispensing BASE_RED base
16:27:35.097080 MPS: Dispense C-BS: BASE_RED
[2019-11-21 16:27:35.216] [C-BS] [info] Sending command: 101 1 0 1
16:27:38.255342 C: Machine C-BS moving base to OUTPUT
[2019-11-21 16:27:43.379] [C-BS] [info] Sending command: 102 3 1 1
16:27:51.415137 C: Machine C-BS: workpiece has been picked up
16:27:56.418501 MPS: Resetting machine C-BS
```

**Comment by pkohout** [comment]
Possible that this picture if from an older version. We were trying to figure out what version works with the simulation and I got a little bit crazy :D. 

Thanks to an email from Till we found out that 2019-beta.1 works with the simulation. 
We updated our Dockercontainer and now we finally can use the simulation again. We will push it to our Dockerhub with the tag simulation (https://hub.docker.com/r/gripstugraz/refbox/). 

Maybe we should think to set up a robocup-logistics dockerhub account where we can host the images. What do you think about that?

**Comment by morxa** [comment]
Good to hear that you have it working!

There is already an RCLL organization on Docker Hub:
https://cloud.docker.com/u/robocuplogistics/repository/list
