### ISSUE TITLE
Machine might be broken after Downtime

### ISSUE THREAD

**Issue by thomerz** [robocup-logistics/rcll-refbox#6]
If a machine is prepared, and immediately after that goes into DOWN state, the machine is broken after it resumes its normal operation due to no product fed in time. I think if a machine goes into DOWN state, the downtime should be added to the time allowed for feeding a product.

**Comment by thomerz** [comment]
Yes, the rules say "extending the overall processing time by the down time" which obviously is the case. However, if you feed a product, prepare the machine, and at that moment the machine goes into DOWN state, the machine afterwards goes into BROKEN state, saying that no product was fed in time.

We actually had this case multiple times in Dornbirn, since the probability was way higher due to only having one CS.

**Comment by timn** [comment]
Ok, to get the timeline clear, let me try this:
```
--- T1 ------------ T2 -----------T3----------T4-----------T5-----------> time
  product          prepare       prepare     machine      machine
  fed into         sent          received    DOWN         back
  machine
```
At T5 the machine now goes into broken, while you expect it to start processing. Between T3 and T4, it did not go into PROCESSING I assume?
In that case I agree, if the prepare was observed by the refbox, but processing had not started, yet, before the machine went down, it should resume normal operation afterwards. That indicates an issue with the handling of the timeout. Can you confirm or amend that assessment, please.

**Comment by thomerz** [comment]
Exactly. AFAIR the time to "feed" a product after prepare is received is 30 seconds, which is then exceeded due to the downtime. Probably Christoph or @MostafaGomaa also have a log file from Dornbirn, since we experienced that behaviour 2 or 3 times during that week.

**Comment by timn** [comment]
Then the fix is simple. In [prod-machine-down](https://github.com/robocup-logistics/rcll-refbox/blob/master/src/games/rcll/production.clp#L29) we need to update the ```wait-for-product-since``` slot similar to the way we update the ```proc-start``` slot.

**Comment by tobiasneumann** [comment]
I don't belive that I was thinking about this case when implementing this.
There are two possible cases to solve that.
1. Tims sollution (results in the time a product can be fed into the machine to 35 sec)
2. Handle the broken state in prod-machine-input, then the input is registered while broken (seems like an intuitive strange behaviour of a machine, but a good solution for rule and fairness vice)

**Comment by timn** [comment]
(BTW, sorry for the delay before. I'm chiming in here since this showed up as a notification now due to the recent activity by @morxa, with our team's workflow having shifted to Github I actually do get the notifications)

**Comment by morxa** [comment]
OK, I misunderstood the initial report. I already implemented the increase for `wait-for-product-since`, but I think it's not really the correct solution. Increasing the time would give the teams more time to feed the workpiece into the machine, but that's not actually correct. We only need to make sure that the machine starts processing before we set it to broken.

Of course, if we do want to give the teams more time, we could adapt the rules and modify `wait-for-product-since`.

**Comment by timn** [comment]
I have pushed a small change that implements what I meant. The idea is, that the time you have to feed a workpiece into a machine is the time while a machine is not `DOWN`. The current fix changes this simply by postponing the start time (and thus also the end time) by the amount the machine is down.

While looking into this, I am a little bit confused about the following line https://github.com/robocup-logistics/rcll-refbox/blob/d4b25c8d7fe256ced296f375debc56d9e4ee8cda/src/games/rcll/production.clp#L549
@tobiasneumann, why should this rule also trigger in processing and processed? This essentially says, that also the processing has to be completed within the time window? Unfortunately we do not have a log, but I'm wondering if that is actually the cause for this problem. There has been a specific commit, https://github.com/robocup-logistics/rcll-refbox/commit/5224295ecd9cf12bb486cda510c33e65474a1e54, which even extended this to `PROCESSED`. Therefore, I guess there was some reasoning behind this. Maybe you can shed some light on this why this is necessary?
