### ISSUE TITLE
Build failure on Fedora 31 due to recent libmicrohttpd changes

### ISSUE THREAD

**Issue by morxa** [robocup-logistics/rcll-refbox#82]
The return type of a number of libmicrohttpd functions changed, quote from the [changelog](https://abi-laboratory.pro/index.php?view=changelog&l=libmicrohttpd&v=0.9.71):

> Wed 08 Apr 2020 10:53:01 PM CEST
    Introduce `enum MHD_Result` for #MHD_YES/#MHD_NO to avoid using 'int' so much.
    Note that this change WILL cause compiler warnings until (most) MHD callbacks
    in application code change their return type from 'int' to 'enum MHD_Result'.
    That said, avoiding possible confusions of different enums is going to make
    the code more robust in the future. For conditional compilation, test
    for "MHD_VERSION >= 0x00097002". -CG

This causes a build failure ([example](https://app.circleci.com/pipelines/github/robocup-logistics/rcll-refbox/94/workflows/74c31618-2d71-4530-9b20-1842e6af6b2c/jobs/791)).

**Comment by vmatare** [comment]
I've started to fix this stuff but I think the 0.9.72 release is borked: https://bugs.gnunet.org/view.php?id=6441

**Comment by vmatare** [comment]
One could work around the inconsistent return types of course, but that would be another special case for a release that should rather be struck from the record

**Comment by vmatare** [comment]
I've rolled back to 0.9.70 and that's what Fedora should do as well.
