### ISSUE TITLE
Run equal game

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/rcll-refbox#85]
Hi,

is there a possibilty to run the same game multiple times (same map, same orders, and so on). Is this planned or isn't that on the roadmap yet?

Thanks a lot,
Peter

**Comment by Schteve-o** [comment]
Hi, 
are there any news on this topic?
Thanks,
Stefan

**Comment by TarikViehmann** [comment]
Oh sorry, i missed the initial issue. If you install mongodb you can enable it in the config and then disable automatic random field generation. 
https://github.com/robocup-logistics/rcll-refbox/blob/93e7f97df176165a216d4a3ece4f9b2cdc73d850/cfg/config.yaml#L151-L164
This enables you to keep the same map. if you also want to fix the orders you could explicitly add a seed to the game parameterization, e.g. after
https://github.com/robocup-logistics/rcll-refbox/blob/93e7f97df176165a216d4a3ece4f9b2cdc73d850/src/games/rcll/game.clp#L56-L65
you could add
```
  (seed 123456)
```
to fix the randomization of orders and such. Not very elegant but it should do the trick.

I might look into configurably loading orders and downtimes etc from mongodb as well, which i guess would be the cleanest solution.

**Comment by pkohout** [comment]
Thanks a lot for the explanation. If I start a game where mongodb is configured, is the first random generated map saved to the DB? And on the next run i can simply disable the `random-field` flag in the config to play on the same field again?

**Comment by TarikViehmann** [comment]
Yes, you can also disable the `random-field` flag directly. If mongodb is configured and no map is stored a field is generated anyways. If you want to re-random the map at any point you can also use the `F1` key in the shell, no need to change the config for that.

**Comment by TarikViehmann** [comment]
you can check out https://github.com/robocup-logistics/rcll-refbox/tree/tviehmann/load-full-games-from-mongodb which allows to fully de-randomize a game by retrieving data from past game reports stored in mongodb. next to `random-field` it provides you with the config values `random-machine-setup` (for ring costs, ring colors per machine and down-times) `random-orders` (for everything related to the order setup) and `random-storage` (for initial `C0`s at storage station). Once the storage station branch is merged i will make a PR for this branch that should resolve this issue. You might have to wipe your previously stored game reports from mongodb before using this branch or alternatively just start a fully randomized game once.

**Comment by pkohout** [comment]
Hi,
we have made some changes to the seeding of the refbox in our local repository so that we can replay the same game again and again (with everything equal like orders, ordertimes and so on....) Is there any interest that we push that also to the master? then we will prepare a Pull Request.

**Comment by TarikViehmann** [comment]
is there anything that is not covered in https://github.com/robocup-logistics/rcll-refbox/tree/tviehmann/load-full-games-from-mongodb already? I will make a PR for that branch once the storage station branch is merged.

**Comment by pkohout** [comment]
it is done via a different approach. Via the mongo db it is possible to replay a game. We have cleaned up the seeding for random numnbers. So all the randomness is only depending on 1 seed. Our goal was to play the 100 same games over and over again. And the workaround with the mongoDB is rather cumberstone to achive this.

**Comment by TarikViehmann** [comment]
True, i think that would be a nice additional feature to have then. So i would welcome if you file a PR for it!

**Comment by TarikViehmann** [comment]
(technically speaking you do not need to do much overhead to play 100 times the same game, just set a name of the saving game report to be the same as the loading game report in the config and set the appropriate randomize flags. That way, if you set a name that u never used before you will get a fresh game setup and every consecutive start of the refbox will simply be the same setup. But independent from that it can be useful to explicitly configure a single seed, e.g., to provide reproducible benchmarks without distributing the game reports alongside which have to be loaded in the db first.)

**Comment by pkohout** [comment]
I think we can close this issue.
