### ISSUE TITLE
Storage Station Integration

### ISSUE THREAD

**Issue by lyndwyrm666** [robocup-logistics/rcll-refbox#86]
In order to integrate the Storage Station into the League we will need to discuss the interface.
Preferably it would look something like this:

- ActionId for Store, Retrieve, Reset
- Data[0] for each storing shelf (0-5)
- Data[1] for each slot in a shelf (0-7)

Band Actions remain the same as CS,RS

**Comment by lyndwyrm666** [comment]
Addressed in #91

**Comment by morxa** [comment]
Please don't close this before the PR is actually merged.

**Comment by TarikViehmann** [comment]
Merged now
